// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Tendermint/proto/tendermint/types/validator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tendermint.Types {

  /// <summary>Holder for reflection information generated from Tendermint/proto/tendermint/types/validator.proto</summary>
  public static partial class ValidatorReflection {

    #region Descriptor
    /// <summary>File descriptor for Tendermint/proto/tendermint/types/validator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValidatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFUZW5kZXJtaW50L3Byb3RvL3RlbmRlcm1pbnQvdHlwZXMvdmFsaWRhdG9y",
            "LnByb3RvEhB0ZW5kZXJtaW50LnR5cGVzGhRnb2dvcHJvdG8vZ29nby5wcm90",
            "bxocdGVuZGVybWludC9jcnlwdG8va2V5cy5wcm90byKKAQoMVmFsaWRhdG9y",
            "U2V0Ei8KCnZhbGlkYXRvcnMYASADKAsyGy50ZW5kZXJtaW50LnR5cGVzLlZh",
            "bGlkYXRvchItCghwcm9wb3NlchgCIAEoCzIbLnRlbmRlcm1pbnQudHlwZXMu",
            "VmFsaWRhdG9yEhoKEnRvdGFsX3ZvdGluZ19wb3dlchgDIAEoAyKCAQoJVmFs",
            "aWRhdG9yEg8KB2FkZHJlc3MYASABKAwSMwoHcHViX2tleRgCIAEoCzIcLnRl",
            "bmRlcm1pbnQuY3J5cHRvLlB1YmxpY0tleUIEyN4fABIUCgx2b3RpbmdfcG93",
            "ZXIYAyABKAMSGQoRcHJvcG9zZXJfcHJpb3JpdHkYBCABKAMiVgoPU2ltcGxl",
            "VmFsaWRhdG9yEi0KB3B1Yl9rZXkYASABKAsyHC50ZW5kZXJtaW50LmNyeXB0",
            "by5QdWJsaWNLZXkSFAoMdm90aW5nX3Bvd2VyGAIgASgDQjlaN2dpdGh1Yi5j",
            "b20vdGVuZGVybWludC90ZW5kZXJtaW50L3Byb3RvL3RlbmRlcm1pbnQvdHlw",
            "ZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tendermint.Crypto.KeysReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tendermint.Types.ValidatorSet), global::Tendermint.Types.ValidatorSet.Parser, new[]{ "Validators", "Proposer", "TotalVotingPower" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tendermint.Types.Validator), global::Tendermint.Types.Validator.Parser, new[]{ "Address", "PubKey", "VotingPower", "ProposerPriority" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tendermint.Types.SimpleValidator), global::Tendermint.Types.SimpleValidator.Parser, new[]{ "PubKey", "VotingPower" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ValidatorSet : pb::IMessage<ValidatorSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ValidatorSet> _parser = new pb::MessageParser<ValidatorSet>(() => new ValidatorSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ValidatorSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tendermint.Types.ValidatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValidatorSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValidatorSet(ValidatorSet other) : this() {
      validators_ = other.validators_.Clone();
      proposer_ = other.proposer_ != null ? other.proposer_.Clone() : null;
      totalVotingPower_ = other.totalVotingPower_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValidatorSet Clone() {
      return new ValidatorSet(this);
    }

    /// <summary>Field number for the "validators" field.</summary>
    public const int ValidatorsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tendermint.Types.Validator> _repeated_validators_codec
        = pb::FieldCodec.ForMessage(10, global::Tendermint.Types.Validator.Parser);
    private readonly pbc::RepeatedField<global::Tendermint.Types.Validator> validators_ = new pbc::RepeatedField<global::Tendermint.Types.Validator>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tendermint.Types.Validator> Validators {
      get { return validators_; }
    }

    /// <summary>Field number for the "proposer" field.</summary>
    public const int ProposerFieldNumber = 2;
    private global::Tendermint.Types.Validator proposer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tendermint.Types.Validator Proposer {
      get { return proposer_; }
      set {
        proposer_ = value;
      }
    }

    /// <summary>Field number for the "total_voting_power" field.</summary>
    public const int TotalVotingPowerFieldNumber = 3;
    private long totalVotingPower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalVotingPower {
      get { return totalVotingPower_; }
      set {
        totalVotingPower_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ValidatorSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ValidatorSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!validators_.Equals(other.validators_)) return false;
      if (!object.Equals(Proposer, other.Proposer)) return false;
      if (TotalVotingPower != other.TotalVotingPower) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= validators_.GetHashCode();
      if (proposer_ != null) hash ^= Proposer.GetHashCode();
      if (TotalVotingPower != 0L) hash ^= TotalVotingPower.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      validators_.WriteTo(output, _repeated_validators_codec);
      if (proposer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Proposer);
      }
      if (TotalVotingPower != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalVotingPower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      validators_.WriteTo(ref output, _repeated_validators_codec);
      if (proposer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Proposer);
      }
      if (TotalVotingPower != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalVotingPower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += validators_.CalculateSize(_repeated_validators_codec);
      if (proposer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proposer);
      }
      if (TotalVotingPower != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalVotingPower);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ValidatorSet other) {
      if (other == null) {
        return;
      }
      validators_.Add(other.validators_);
      if (other.proposer_ != null) {
        if (proposer_ == null) {
          Proposer = new global::Tendermint.Types.Validator();
        }
        Proposer.MergeFrom(other.Proposer);
      }
      if (other.TotalVotingPower != 0L) {
        TotalVotingPower = other.TotalVotingPower;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            validators_.AddEntriesFrom(input, _repeated_validators_codec);
            break;
          }
          case 18: {
            if (proposer_ == null) {
              Proposer = new global::Tendermint.Types.Validator();
            }
            input.ReadMessage(Proposer);
            break;
          }
          case 24: {
            TotalVotingPower = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            validators_.AddEntriesFrom(ref input, _repeated_validators_codec);
            break;
          }
          case 18: {
            if (proposer_ == null) {
              Proposer = new global::Tendermint.Types.Validator();
            }
            input.ReadMessage(Proposer);
            break;
          }
          case 24: {
            TotalVotingPower = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Validator : pb::IMessage<Validator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Validator> _parser = new pb::MessageParser<Validator>(() => new Validator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Validator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tendermint.Types.ValidatorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Validator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Validator(Validator other) : this() {
      address_ = other.address_;
      pubKey_ = other.pubKey_ != null ? other.pubKey_.Clone() : null;
      votingPower_ = other.votingPower_;
      proposerPriority_ = other.proposerPriority_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Validator Clone() {
      return new Validator(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private pb::ByteString address_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pub_key" field.</summary>
    public const int PubKeyFieldNumber = 2;
    private global::Tendermint.Crypto.PublicKey pubKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tendermint.Crypto.PublicKey PubKey {
      get { return pubKey_; }
      set {
        pubKey_ = value;
      }
    }

    /// <summary>Field number for the "voting_power" field.</summary>
    public const int VotingPowerFieldNumber = 3;
    private long votingPower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long VotingPower {
      get { return votingPower_; }
      set {
        votingPower_ = value;
      }
    }

    /// <summary>Field number for the "proposer_priority" field.</summary>
    public const int ProposerPriorityFieldNumber = 4;
    private long proposerPriority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ProposerPriority {
      get { return proposerPriority_; }
      set {
        proposerPriority_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Validator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Validator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Address != other.Address) return false;
      if (!object.Equals(PubKey, other.PubKey)) return false;
      if (VotingPower != other.VotingPower) return false;
      if (ProposerPriority != other.ProposerPriority) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (pubKey_ != null) hash ^= PubKey.GetHashCode();
      if (VotingPower != 0L) hash ^= VotingPower.GetHashCode();
      if (ProposerPriority != 0L) hash ^= ProposerPriority.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Address);
      }
      if (pubKey_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PubKey);
      }
      if (VotingPower != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(VotingPower);
      }
      if (ProposerPriority != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ProposerPriority);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Address);
      }
      if (pubKey_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PubKey);
      }
      if (VotingPower != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(VotingPower);
      }
      if (ProposerPriority != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ProposerPriority);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Address);
      }
      if (pubKey_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PubKey);
      }
      if (VotingPower != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(VotingPower);
      }
      if (ProposerPriority != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProposerPriority);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Validator other) {
      if (other == null) {
        return;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.pubKey_ != null) {
        if (pubKey_ == null) {
          PubKey = new global::Tendermint.Crypto.PublicKey();
        }
        PubKey.MergeFrom(other.PubKey);
      }
      if (other.VotingPower != 0L) {
        VotingPower = other.VotingPower;
      }
      if (other.ProposerPriority != 0L) {
        ProposerPriority = other.ProposerPriority;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Address = input.ReadBytes();
            break;
          }
          case 18: {
            if (pubKey_ == null) {
              PubKey = new global::Tendermint.Crypto.PublicKey();
            }
            input.ReadMessage(PubKey);
            break;
          }
          case 24: {
            VotingPower = input.ReadInt64();
            break;
          }
          case 32: {
            ProposerPriority = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Address = input.ReadBytes();
            break;
          }
          case 18: {
            if (pubKey_ == null) {
              PubKey = new global::Tendermint.Crypto.PublicKey();
            }
            input.ReadMessage(PubKey);
            break;
          }
          case 24: {
            VotingPower = input.ReadInt64();
            break;
          }
          case 32: {
            ProposerPriority = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SimpleValidator : pb::IMessage<SimpleValidator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SimpleValidator> _parser = new pb::MessageParser<SimpleValidator>(() => new SimpleValidator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SimpleValidator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tendermint.Types.ValidatorReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleValidator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleValidator(SimpleValidator other) : this() {
      pubKey_ = other.pubKey_ != null ? other.pubKey_.Clone() : null;
      votingPower_ = other.votingPower_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleValidator Clone() {
      return new SimpleValidator(this);
    }

    /// <summary>Field number for the "pub_key" field.</summary>
    public const int PubKeyFieldNumber = 1;
    private global::Tendermint.Crypto.PublicKey pubKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tendermint.Crypto.PublicKey PubKey {
      get { return pubKey_; }
      set {
        pubKey_ = value;
      }
    }

    /// <summary>Field number for the "voting_power" field.</summary>
    public const int VotingPowerFieldNumber = 2;
    private long votingPower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long VotingPower {
      get { return votingPower_; }
      set {
        votingPower_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SimpleValidator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SimpleValidator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PubKey, other.PubKey)) return false;
      if (VotingPower != other.VotingPower) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pubKey_ != null) hash ^= PubKey.GetHashCode();
      if (VotingPower != 0L) hash ^= VotingPower.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pubKey_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PubKey);
      }
      if (VotingPower != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(VotingPower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pubKey_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PubKey);
      }
      if (VotingPower != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(VotingPower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pubKey_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PubKey);
      }
      if (VotingPower != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(VotingPower);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SimpleValidator other) {
      if (other == null) {
        return;
      }
      if (other.pubKey_ != null) {
        if (pubKey_ == null) {
          PubKey = new global::Tendermint.Crypto.PublicKey();
        }
        PubKey.MergeFrom(other.PubKey);
      }
      if (other.VotingPower != 0L) {
        VotingPower = other.VotingPower;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pubKey_ == null) {
              PubKey = new global::Tendermint.Crypto.PublicKey();
            }
            input.ReadMessage(PubKey);
            break;
          }
          case 16: {
            VotingPower = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (pubKey_ == null) {
              PubKey = new global::Tendermint.Crypto.PublicKey();
            }
            input.ReadMessage(PubKey);
            break;
          }
          case 16: {
            VotingPower = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
