name: Deploy Testnet

on:
  workflow_dispatch:

jobs:
  build:
    name: Test my .Net
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Step .NET
        uses: actions/checkout@v2

      - name: Run echo
        run: echo 'lorem'